- hosts: localhost
  tasks:
    - import_tasks: Archlinux/tasks.yml
      when: ansible_facts['os_family']|lower == 'archlinux'
    - include_vars: Archlinux/setup.yml
      when: ansible_facts['os_family']|lower == 'archlinux'
    - import_tasks: Debian/tasks.yml
      when: ansible_facts['os_family']|lower == 'debian'
    - include_vars: Debian/setup.yml
      when: ansible_facts['os_family']|lower == 'debian'


    - name: Install native packages
      become: yes
      package:
        name: 
          - "{{snapd}}"
          - "{{flatpak}}"
          - "{{python}}"
          - "{{pip}}"
          - "{{docker}}"
          - "{{openjdk}}"
          - "{{openjre}}"
          - "{{dotnetre}}"
          - "{{dotnetsdk}}"
        state: present

    - name: Install snaps with classic confinement
      snap:
        name:
          - code
          - intellij-idea-community
        classic: yes
        state: present

    - name: Install snaps
      snap:
        name:
          - discord
          - gitkraken
          - obs-studio
        state: present
    
    - name: Install NeoVim
      snap:
        name:
          - nvim
        state: present
        classic: yes
        channel: beta

    - name: Install Flatpaks
      flatpak:
        name: com.valvesoftware.Steam
        state: present

    - name: Install global Pip packages
      pip:
        name:
          - pipenv
        state: present
    
    - name: Install Simple Docker images
      docker_image:
        name:
          - miktex/miktex
        pull: yes
        state: present
