- hosts: localhost
  tasks:
    - import_tasks: Archlinux/tasks.yml
      when: ansible_facts['os_family']|lower == 'archlinux'
    - include_vars: Archlinux/setup.yml
      when: ansible_facts['os_family']|lower == 'archlinux'
    - import_tasks: Debian/tasks.yml
      when: ansible_facts['os_family']|lower == 'debian'
    - include_vars: Debian/setup.yml
      when: ansible_facts['os_family']|lower == 'debian'


    - name: Install native packages
      become: yes
      package:
        name:
          - "{{snapd}}"
          - "{{flatpak}}"
          - "{{python}}"
          - "{{pip}}"
          - "{{openjdk}}"
          - "{{openjre}}"
          - "{{dotnetre}}"
          - "{{dotnetsdk}}"
        state: present

    - name: Install snaps with classic confinement
      snap:
        name:
          - code
          - intellij-idea-community
        classic: yes
        state: present

    - name: Install snaps
      snap:
        name:
          - discord
          - obs-studio
          - docker
        state: present

    - name: Install NeoVim
      snap:
        name:
          - nvim
        state: present
        classic: yes
        channel: beta

    - name: Install Flatpaks
      flatpak:
        name: com.valvesoftware.Steam
        state: present

    - name: Install global Pip packages
      pip:
        name:
          - pipenv
        state: present

    - name: Install Rustup
      shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

    - name: Install NVM
      shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash

    - name: Install vim-plug
      shell: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
